# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0BCUAw38g1R9eNIYw_1mNAN4KuMEujN
"""

print("Hello, Python is working in Google Colab!")



import smtplib
import pandas as pd
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from google.colab import files

# Upload and Load Excel
uploaded = files.upload()
df = pd.read_excel("email1.xlsx")  # Ensure correct filename
df.columns = df.columns.str.strip().str.upper()  # Fix column names

# Email credentials
sender_email = "richardsamuelr85@gmail.com"
password = "ihys edrm dtej lshk"

# SMTP Setup
server = smtplib.SMTP("smtp.gmail.com", 587)
server.starttls()
server.login(sender_email, password)

# Loop through recipients
for index, row in df.iterrows():
    receiver_email = row['EMAIL']  # Now uses corrected column name
    name = row['NAME']

    # Compose email
    msg = MIMEMultipart()
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg["Subject"] = "Automated Email"
    body = f"Hello {name},\n\nThis is an automated email sent from Python script.\n\nThanks!"
    msg.attach(MIMEText(body, "plain"))

    # Send email
    server.sendmail(sender_email, receiver_email, msg.as_string())
    print(f"Email sent to {receiver_email}")

# Close server
server.quit()